name: blog_website_actions
run-name: showing the database
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: echo the current string
      run: echo "I am echoing the given string"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: my database contents
      run: mysql -h ${{ secrets.DB_HOST }} --port ${{ secrets.DB_PORT }} -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }}
    - name: running scripts from sql query file on github
      run: mysql -h ${{ secrets.DB_HOST }} --port ${{ secrets.DB_PORT }} -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source blog-website/blog_website_mysql_database.sql"